# Generated by Django 3.1.7 on 2021-06-18 20:57

import apps.secr_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_court', models.CharField(max_length=45)),
                ('comuna', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Defendant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name1', models.CharField(max_length=45, validators=[apps.secr_app.models.ValidarLongitud])),
                ('first_name2', models.CharField(max_length=45, validators=[apps.secr_app.models.ValidarLongitud])),
                ('last_name1', models.CharField(max_length=45, validators=[apps.secr_app.models.ValidarLongitud])),
                ('last_name2', models.CharField(max_length=45, validators=[apps.secr_app.models.ValidarLongitud])),
                ('address', models.CharField(max_length=255, validators=[apps.secr_app.models.ValidarLongitud])),
                ('rut', models.CharField(max_length=10, validators=[apps.secr_app.models.ValidarRut])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('defendant_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_create_defendant', to='users_app.administrator')),
            ],
        ),
        migrations.CreateModel(
            name='Lawsuit_State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_state', models.CharField(max_length=45)),
                ('demand_state', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lawsuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_promissory_notes', models.CharField(max_length=45)),
                ('final_date', models.DateField(validators=[apps.secr_app.models.Validar_Fecha_Mora])),
                ('mount_to_pay', models.CharField(max_length=255, validators=[apps.secr_app.models.Validar_Monto_a_Pagar])),
                ('num_operation', models.CharField(max_length=255)),
                ('suscription_date', models.DateField(validators=[apps.secr_app.models.Validar_Fecha_Suscripcion])),
                ('demand_amount', models.IntegerField(validators=[apps.secr_app.models.Validar_Monto_Demandado])),
                ('cause_rol', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_court_lawsuits', to='secr_app.lawsuit_state')),
                ('current_defendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defendant_lawsuit', to='secr_app.defendant')),
                ('current_demand_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_demand_lawsuits', to='secr_app.lawsuit_state')),
                ('lawsuit_administrated_by', models.ManyToManyField(related_name='user_administrate_lawsuit', to='users_app.User')),
            ],
        ),
    ]
